# This file was generated by GoReleaser. DO NOT EDIT.
cask "libscan" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "f6b0d06dcbb9be96f3c6ecc7420150711c0e59f77e62af3b49560e2cf8353f02"
      url "https://github.com/vocweb/libscan-cli/releases/download/v#{version}/libscan-cli_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "66a5df54eb40df1ffa2f5ca3577886f2c04f130ff1274568ff82fc79a60e231b"
      url "https://github.com/vocweb/libscan-cli/releases/download/v#{version}/libscan-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a16a27b9c4654353ed1c2c431b50a7fd09e2f73c2478307d03f82c5a1f840a7"
      url "https://github.com/vocweb/libscan-cli/releases/download/v#{version}/libscan-cli_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ef4c6d0adfb4b13f9c289f9879ad5a337f3a727e049b32c1960c3fee526faa39"
      url "https://github.com/vocweb/libscan-cli/releases/download/v#{version}/libscan-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "libscan"
  desc "Scan PHP / Node.js projects for outdated and vulnerable dependencies (CVE + EOL)."
  homepage "https://github.com/vocweb/libscan-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "libscan"

  # No zap stanza required

end
